### ISSUE TITLE
Add metadata to schema

### ISSUE THREAD

**Issue by jmcvetta** [rollbar/terraform-provider-rollbar#68]
Terraform SDK v2 (which we're already using) added [support for metadata](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#support-for-resource-level-and-field-level-descriptions) on resources and fields.  This is not yet actually used by Terraform for anything, but will be used in a future version.  So we ought to add this now.  

> it’s recommended that you set these properties to whatever you’d document the resource or field as in your terraform.io docs for the resource.

## Todo

* [x] resource `rollbar_project`
* [x] resource `rollbar_projec_access_token`
* [x] resource `rollbar_team`
* [x] resource `rollbar_user`
* [x] data source `rollbar_project`
* [x] data source `rollbar_projects`
* [x] data source `rollbar_project_access_token`
* [ ] data source `rollbar_project_access_tokens`
